version: '3.1'
services:
  nginx:
    restart: always
    image: nginx:1.17.5
    container_name: nginx
    ports:
      - 81:80
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./wwwroot:/usr/share/nginx/wwwroot
