version: '3.1'
services:
  mysql:
    image: mysql:8.0.16
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql

  adminer:
    image: adminer:4.7.3
    restart: always
    container_name: adminer
    ports:
      - 8081:8080